::EUR.EUR_OPTION_TABS.append({
    title = "Campaign",
    sections = [
        [
            { button = "Restore default settings", showFn = function() { return ::EUR.options_first_run },
              tip = "Restores the default settings for this menu and not those saved from previous campaigns.",
              onClick = function() { ::game.runScriptCommand("play_sound_event", "BUTTON_DOWN"); ::EUR.restoreDefaultSettings() } },
            { label = "Replenishment" },
            { check = "Enabled",                  bind = ["options_replen"],       tip = "Enable replenishment." },
            { check = "Low Entity Units",         bind = ["options_replen_beast"], tip = "Enables replenishment for low entity units such as Trolls, Ents, Skin-changers etc.",
              onChange = function(v) { ::EUR.replen_beast_value = v ? 0 : 10 } },
            { check = "Field Replenishment",      bind = ["replen_always"],        tip = "Enables replenishment for non-garrisoned armies." },
            { check = "Replenishment costs gold", bind = ["options_replen_costs"],  tip = "Enable gold deduction for replenishment, based on recruitment cost." },
            { slider = "Replenishment cost multiplier", bind = ["replen_cost_multi"], min = 10, max = 100, fmt = "%d%%", tip = "Default 50% (half cost).", showIf = "options_replen_costs" },

            { expand = "Advanced", body = [
                { slider = "Flat Global Bonus", min = 0, max = 50, fmt = "%d%%", tip = "Global bonus applies to all multipliers.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_bonus)) },
                  set = function(v) { ::EUR.replen_values.replen_bonus = ::EUR.safe_round_divide(100, v) } },
                { slider = "Garrisoned rate", min = 0, max = 15, fmt = "%d%%", tip = "Applies if a unit is garrisoned in a settlement or fort.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_multi)) },
                  set = function(v) { ::EUR.replen_values.replen_multi = ::EUR.safe_round_divide(100, v) } },
                { slider = "Waystation bonus", min = 0, max = 15, fmt = "%d%%", tip = "Applies if the Waystation building is present in the settlement.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.waystation_bonus)) },
                  set = function(v) { ::EUR.replen_values.waystation_bonus = ::EUR.safe_round_divide(100, v) } },
                { slider = "Health bonus", min = 0, max = 15, fmt = "%d%%", tip = "Applies if the second level Health building is present in the settlement.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.aquaduct_bonus)) },
                  set = function(v) { ::EUR.replen_values.aquaduct_bonus = ::EUR.safe_round_divide(100, v) } },
                { slider = "Dirt roads", min = 0, max = 15, fmt = "%d%%", tip = "Applies if dirt roads are present in the region.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_road_level[1])) },
                  set = function(v) { ::EUR.replen_values.replen_road_level[1] = ::EUR.safe_round_divide(100, v) } },
                { slider = "Paved roads", min = 0, max = 15, fmt = "%d%%", tip = "Applies if paved roads are present in the region.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_road_level[2])) },
                  set = function(v) { ::EUR.replen_values.replen_road_level[2] = ::EUR.safe_round_divide(100, v) } },
                { slider = "Highways", min = 0, max = 15, fmt = "%d%%", tip = "Applies if trade route (Highways) are present in the region.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_road_level[3])) },
                  set = function(v) { ::EUR.replen_values.replen_road_level[3] = ::EUR.safe_round_divide(100, v) } },
                { slider = "Own / Allied territory", min = 0, max = 15, fmt = "%d%%", tip = "Base rate for field armies in friendly territory, road level also applies.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_field_own)) },
                  set = function(v) { ::EUR.replen_values.replen_field_own = ::EUR.safe_round_divide(100, v) } },
                { slider = "Enemy / Neutral territory", min = 0, max = 15, fmt = "%d%%", tip = "Base rate for field armies in non-friendly territory, road level also applies.",
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.replen_field_other)) },
                  set = function(v) { ::EUR.replen_values.replen_field_other = ::EUR.safe_round_divide(100, v) } },
                { slider = "Goblin bonus", min = 0, max = 15, fmt = "%d%%", tip = "Bonus for Orc and Goblin factions.",
                  showFn = function() { return ::EUR.eur_player_faction != null && ::EUR.tableContains(::EUR.goblin_factions, ::EUR.eur_player_faction.name) },
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.goblin_bonus)) },
                  set = function(v) { ::EUR.replen_values.goblin_bonus = ::EUR.safe_round_divide(100, v) } },
                { slider = "Human bonus", min = 0, max = 15, fmt = "%d%%", tip = "Bonus for Human factions.",
                  showFn = function() { return ::EUR.eur_player_faction != null && ::EUR.tableContains(::EUR.men_factions, ::EUR.eur_player_faction.name) },
                  get = function() { return ::EUR.round_half(::EUR.safe_divide(100, ::EUR.replen_values.men_bonus)) },
                  set = function(v) { ::EUR.replen_values.men_bonus = ::EUR.safe_round_divide(100, v) } },
            ] },
        ],
        [
            { sep = true },
            { label = "Army Sorting" },
            { check = "Enabled", bind = ["options_sort"], tip = "Enable army sorting." },
            { label = "Sort order:" },
            { select = "First",  bind = ["sort_order", "a"], options = ["EDU Name", "Category (eg infantry)", "Class (eg heavy)", "Soldier Count", "Experience", "(Default) Category + Class", "AI unit value"] },
            { select = "Second", bind = ["sort_order", "b"], options = ["(Default) EDU Name", "Category (eg infantry)", "Class (eg heavy)", "Soldier Count", "Experience", "Category + Class", "AI unit value"] },
            { select = "Third",  bind = ["sort_order", "c"], options = ["EDU Name", "Category (eg infantry)", "Class (eg heavy)", "(Default) Soldier Count", "Experience", "Category + Class", "AI unit value"] },
        ],
        [
            { sep = true },
            { label = "Global Recruitment" },
            { check = "Enabled", bind = ["game_options", "global_recruitment"], tip = "Enable Global Recruitment." },
            { slider = "Global queue starting size", bind = ["game_options", "global_recruit_start"], min = 1, max = 20, fmt = "%d", tip = "Global Recruitment starting size (default 2)." },
            { slider = "Global queue limit", bind = ["game_options", "global_recruit_max"], min = 2, max = 20, fmt = "%d", tip = "Global Recruitment queue max size (default 10)." },
            { check = "Waystation increases global queue size", bind = ["game_options", "global_waystation_inc_max"], tip = "Constructing Waystations increases the Global Recruitment queue size (disable to simply use the max queue size)." },
            { check = "Hide settlements without units", bind = ["game_options", "global_recruitment_hidenounits"], tip = "Hide settlements that have no units to recruit, or have all their recruited units hidden." },
            { check = "Waystation required in settlement", bind = ["game_options", "global_waystation_req"], tip = "Require a Waystation to be constructed in the settlement in order to receive global recruits." },
            { check = "Local recruits only", bind = ["game_options", "global_recruitment_localonly"], tip = "Enables the UI but you can only recruit locally." },
            { check = "Sort alphabetically", bind = ["game_options", "global_sort_aphabetically"], tip = "Sort settlements in the UI alphabetically.",
              onChange = function(v) { if (v) ::EUR.game_options.global_sort_distance = false } },
            { check = "Sort by distance", bind = ["game_options", "global_sort_distance"], tip = "Sort settlements in the UI by distance to the local settlement.",
              onChange = function(v) { if (v) ::EUR.game_options.global_sort_aphabetically = false } },
        ],
        [
            { sep = true },
            { label = "Faction Revival" },
            { stepper = "Revival cost", bind = ["game_options", "revival_cost"], min = 1000, max = 50000, step = 1000, tip = "Faction revival cost." },
            { check = "Unlimited revivals", bind = ["game_options", "unlimited_revival"], tip = "Revive factions an unlimited number of times." },
            { check = "AI revivals", bind = ["game_options", "airevive"], tip = "AI factions have a chance to revive on their own, provided that the player does not own their capital." },
            { check = "Ignore disposition", bind = ["game_options", "revival_disposition_ignored"], tip = "Allow any faction to revive any other.",
              onChange = function(v) {
                  if (!v) { foreach (k, val in ::EUR.faction_disposition_default) { ::EUR.faction_disposition[k] = val } }
                  else { foreach (k, val in ::EUR.faction_disposition) { ::EUR.faction_disposition[k] = "neutral" } }
              } },
        ],
        [
            { sep = true },
            { label = "Campaign Miscellaneous", tip = "Campaign Miscellaneous." },
            { slider = "Watchtower sight range", bind = ["watchtower_range"], min = 10, max = 50, fmt = "%d", tip = "Default 10." },
            { check = "Allied vision", bind = ["game_options", "reveal_allied"], tip = "Reveal fog of war around allied settlements and armies." },
            { check = "Evolving Faction Names", bind = ["options_evolvingnames"], tip = "AI faction names change depending on their size." },
            { check = "Constructable Forts", bind = ["build_forts"], tip = "Build permanent forts in owned regions, scaled costs depending on how many forts are present." },
            { check = "Autosaves", bind = ["game_options", "auto_saves_enabled"], tip = "Enable end turn rolling autosaves." },
            { check = "Settlement messages", bind = ["game_options", "siege_messages"], tip = "Enable events for AI settlement loss, such as capitals.",
              onChange = function(v) { ::game.campaign().setEventCounter("sieged_messages", v ? 1 : 0) } },
            { check = "Post-battle loot", bind = ["options_addspoils"], tip = "After winning a battle, the player has a chance of looting the enemy baggage train." },
            { check = "AI Army merging", bind = ["options_merge"], tip = "Smaller AI armies will merge every few turns, reducing stack clutter." },
            { check = "AI Eregion", bind = ["game_options", "eregion_spawn"], tip = "Spawns Eregion as a faction during the campaign, even when not playing as Lindon or Imladris. Eregion spawns between turns 60-80." },
            { check = "Convert Buildings", bind = ["game_options", "convert_buildings"], tip = "Automatically converts like for like buildings to the settlement owner's culture over the end turn." },
            { check = "AI Garrisons", bind = ["game_options", "garrisons"], tip = "Enable Garrisons in key AI settlements (not recommended to disable as the AI may lose those settlements earlier)." },
        ],
    ],
})
