// Units excluded from the per-faction upgrade picker. Ported from the table at the top of
// eopData/eopScripts/eur/options/eurOptionsUpgrades.lua - it was never carried over, so
// player_units_cut stayed empty and buildPlayerUnits raised on the first faction it looked up.
::EUR.player_units_cut <- {
    ["egypt"] = [
        "Heavy Falathrim Wavebreakers",
        "Heavy Falathrim Spears",
    ],
    ["poland"] = [
        "Sauron",
        "Troll Drummers",
        "Mirkwood Trolls",
        "Forest Trolls",
        "Olog-hai",
        "Giant Spiders",
        "Mirkwood Catapult",
        "Mirkwood Ballista",
        "Mordor Catapult",
        "Orc Garrison Elite",
        "Guldur Heavy Swords Garrison",
        "Khamuls Shadow Rangers Garrison",
        "Khamul's Chosen Garrison",
        "Bolgs Champions Garrison"
    ],
    ["teutonic_order"] = [
        "Fylani War Wagons",
        "Westron Ballista",
        "Westron Catapult",
        "Wildmen Garrison Elite",
        "Tir Croicoill Cosantoiri Garrison",
        "Enedwaith Marksmen Garrison",
        "Liadan Billmen Garrison",
        "Warband Blades Garrison",
        "Human Boat"
    ],
    ["norway"] = [
        "Beorning Axemen",
        "Beekeepers",
        "Eotheod Horsemen",
        "Dwarven Ballista",
        "Dwarven Catapult",
        "Axeguard of Erebor Garrison",
        "Kings Warriors Garrison",
        "Legion Deeping Guard Garrison",
        "Legion Crossbows Garrison",
        "Khazad-dum Guardians Garrison",
        "Khazad-dum Reclaimers Garrison"
    ],
    ["ireland"] = [
        "Ents",
        "Elven Ballista",
        "Elven Catapult",
        "Ent Catapult",
        "Elvenking's Swordguard Garrison",
        "Hin e-Daur Garrison",
        "Elvenking's Palace Guard Garrison",
        "Galadhrim Archers Garrison",
        "Galadhrim Swordsmen Garrison",
        "Galadhrim Guards Garrison",
        "Human Boat"
    ],
    ["france"] = [
        "Troll Drummers",
        //"Warg Marauders",
        "Bolgs Champions",
        "Lego Uruk-hai Infantry",
        "Lego Berserkers",
        "Trolls of the White Hand",
        "Trolls",
        "Olog-hai",
        "Isengard Ballista",
        "Snaga Catapult",
        "Orc Garrison Elite",
        "Uruk-hai Crossbow Garrison",
        "Uruk-hai Infantry Garrison",
        "Uruk-hai Spearguard Garrison",
        "Bolgs Champions Garrison"
    ],
    ["normans"] = [
        "Goblin King",
        "Wolf Pack",
        "Dourhand Crossbows",
        "Beleriand Wolves",
        "Cave Troll Drummers",
        "White Wolves",
        "Moria Balrog",
        "Warg Pack",
        "Trolls",
        "Armored Balrog",
        "Crag Trolls",
        "Armoured Crag Trolls",
        "Blue Crag Troll Hurlers",
        "Cave Trolls",
        "Blue Crag Catapult",
        "Dourhand Catapult",
        "Dourhand Barrel Thrower",
        "Crag Siege Trolls",
        "Blue Crag Ballista Tower",
        "Snaga Ballista",
        "Snaga Catapult",
        "Blue Crag Ballista",
        "Blue Crag Orc Javs Garrison",
        "Crag Trolls Garrison",
        "Blue Crag Berserkers Garrison",
        "Blue Crag Goblin Axes Garrison",
        "Blue Crag Goblin Slingers Garrison"
    ],
    ["denmark"] = [
        "Dunedain Bodyguard Twins",
        "Lindon Chariot",
        "Noldor Chariot",
        "Elven Ballista",
        "Elven Catapult",
        "Noldorin Veterans Garrison",
        "Elderinwe Tirno Garrison",
        "Heavy Falathrim Archers Garrison",
        "Heavy Falathrim Wavebreakers Garrison",
        "Mithlond Nobles Garrison",
        "Elven Ship",
        "Elven Boat"
    ],
    ["portugal"] = [
        "Black Trolls of Angmar",
        "Snow Trolls",
        "Angmar Ballista",
        "Angmar Catapult",
        "Orc Garrison Elite",
        "Blackshield Archers Garrison",
        "Iron Crown Warriors Garrison",
        "Iron Crown Longbowmen Garrison",
        "Northguard Garrison",
        "Blackshield Warriors Garrison",
        "Human Boat"
    ],
    ["turks"] = [
        "Riders of the Green Hills2",
        "Anfalas Bodyguard2",
        "Lossarnach Household Guard2",
        "The White Company2",
        "Ringlo House Guards2",
        "Dunedain Bodyguard Twins",
        "Azrazair Raiders",
        "Peasant Militia",
        "Eorling Archers",
        "Rohirrim",
        "Lego Rohirrim",
        "Rohirrim Archers",
        "Riddermark Axemen",
        "Eored Lancers",
        "Eored Skirmishers",
        "Riders of the Fold",
        "Golden Hall Spearmen",
        "Royal Guard",
        "Northmen Militia",
        "Dalian Billmen",
        "Dalian Longbowmen",
        "Lake-town Pikemen",
        "Barding Marksmen",
        "Barding Hird",
        "Aihwothiuda Horseguards",
        "Thorn Bladesmen",
        "Thorn Guard",
        "Thorn Crossbowmen",
        "Regent Axeguard",
        "Regent Spearguard",
        "Regent Bowguard",
        "Beorning Axemen",
        "Vale Archers",
        "Beekeepers",
        "Woodman Warriors",
        "Woodman Hunters",
        "Woodman Wardens",
        "Eotheod Archers",
        "Greenwood Foresters",
        "Rhudaur Savages",
        "Hillmen",
        "Rhudaur Huscarles",
        "Ettenmoors Troll-Hunters",
        "Rhudaur Spearmen",
        "Rhudaur Warriors",
        "Angmarim Warriors",
        "Angmarim Pikes",
        "Dreadguard",
        "Clan Axemen",
        "Clan Spearmen",
        "Clan Hunters",
        "Frekkalingir Hill-Riders",
        "Dunhird Berserkers",
        "Dunlending Longspears",
        "Dunhird Warriors",
        "Warband Sentries",
        "Wulfguard Axemen",
        "Wulfguard Pikes",
        "Orthanc Warden",
        "Orthanc Guard",
        "Mordag Fishermen",
        "Mochaini Touta",
        "Keefei Huntsmen",
        "Liadan Billmen",
        "Mordag Skirmishers",
        "Fylani Herders",
        "Enedwaith Guardsmen",
        "Enedwaith Marksmen",
        "Haradrim Spearmen",
        "Haradrim Archers",
        "Southron Warband",
        "Southron Pikemen",
        "Southron Archers",
        "Muhad Tribesmen",
        "Muhad Beastmasters",
        "Troll-men Warriors",
        "Troll-men Hunters",
        "Steppe Tribesmen",
        "Steppe Archers",
        "Nomad Axemen",
        "Khandish Raiders",
        "Nomad Horsemen",
        "Daritai Clansmen",
        "Rhunnic Spears",
        "Rhunnic Warriors",
        "Claw-Guard",
        "Loke-Rim Swordsmen",
        "Loke-Rim Spearmen",
        "Kar's Chosen",
        //"Merchant Cavalry",
        "Amanyar Swordmasters",
        "Oathbreakers",
        //"Greenway Spearmen",
        //"Journeymen",
        //"Woodland Hunters",
        "Saralainn Mercenaries",
        "Harondor Mercenaries",
        "Farrhun Mercenaries",
        "Eriador Ballista",
        "Eriador Catapult",
        "Eriador Trebuchet",
        "Hobbit Ranchers Garrison",
        "Bandobras Archers Garrison",
        "Hobbit Infantry Garrison",
        "Watch Shirriffs Garrison",
        "Watchmen Swordguard Garrison",
        "Watchmen Axeguard Garrison",
        "Watchmen Bowguard Garrison",
        "Greenway Spearmen Garrison",
        "Journeymen Garrison",
        "Dunedain Garrison",
        "Enedwaith Marksmen Garrison",
        "Liadan Billmen Garrison",
        "Warband Sentries Garrison",
        "Wulfguard Axemen Garrison",
        "Regent Axeguard Garrison",
        "Regent Bowguard Garrison",
        "Lake-town Pikemen Garrison",
        "Golden Hall Spearmen Garrison",
        "Dunedain Axemen Garrison",
        "Dunedain Rangers Garrison",
        "Southron Pikemen Garrison",
        "Southron Archers Garrison",
        "Fountain Guard Garrison",
        "Lossarnach Axemen Garrison",
        "Guards of Osgiliath Garrison",
        "Osgiliath Veterans Garrison",
        "Raven Helms of Cair Andros Garrison",
        "Gondor Garrison Infantry",
        "Gondor Garrison Archers",
        "Gondor Boat",
        "Gondor Ship"
    ],
    ["england"] = [
        "Sauron",
        "Mordor Trolls",
        "Mirkwood Trolls",
        "Forest Trolls",
        "Olog-hai",
        "Great Beasts",
        "Giant Spiders",
        "Farrhun Mercenaries",
        "Orc Catapult",
        "Orc Ballista",
        "Mordor Catapult",
        "Orc Garrison Elite",
        "Loke-Rim Pikemen Garrison",
        "Variag Swordsmen Garrison",
        "Bolgs Champions Garrison",
        "Temple Marksmen Garrison",
        "Temple Wards Garrison",
        "Barad-dur Wardens Garrison",
        "Morgul Durburz Garrison",
        "Morannon Gathrak Garrison",
        "Black Uruks Garrison",
        "Black Uruk Halberd Garrison"
    ],
    ["hre"] = [
        "Goblin King",
        "Cave Troll Drummers",
        "Moria Balrog",
        "Warg Pack",
        "Trolls",
        "Armored Balrog",
        "Crag Trolls",
        "Armoured Crag Trolls",
        "Blue Crag Troll Hurlers",
        "Cave Trolls",
        "Dourhand Catapult",
        "Dourhand Barrel Thrower",
        "Crag Siege Trolls",
        "Blue Crag Ballista Tower",
        "Snaga Ballista",
        "Snaga Catapult",
        "Mordor Catapult",
        "Misty Mangonel",
        "Blue Crag Ballista",
        "Blue Crag Orc Javs Garrison",
        "Crag Trolls Garrison",
        "Orc Garrison Elite",
        "Blue Crag Berserkers Garrison",
        "Blue Crag Goblin Axes Garrison",
        "Blue Crag Goblin Slingers Garrison",
        "Black Pit Infantry Garrison",
        "Black Pit Crossbows Garrison",
        "Mountain Uruks Garrison",
        "Bolgs Champions Garrison"
    ],
    ["gundabad"] = [
        "Cave Troll Drummers",
        "White Wolves",
        "Lego Berserkers",
        "Troll Avengers",
        "Black Trolls of Angmar",
        "Snow Trolls",
        "Great Beasts",
        "Crag Trolls",
        "Armoured Crag Trolls",
        "Blue Crag Troll Hurlers",
        "Dourhand Catapult",
        "Dourhand Barrel Thrower",
        "Crag Siege Trolls",
        "Blue Crag Ballista Tower",
        "Snaga Ballista",
        "Snaga Catapult",
        "Blue Crag Ballista",
        "Blue Crag Orc Javs Garrison",
        "Crag Trolls Garrison",
        "Orc Garrison Elite",
        "Blackshield Archers Garrison",
        "Blue Crag Berserkers Garrison",
        "Blue Crag Goblin Axes Garrison",
        "Blue Crag Goblin Slingers Garrison",
        "Guldur Heavy Swords Garrison",
        "Black Pit Crossbows Garrison",
        "Mountain Uruks Garrison",
        "Bolgs Champions Garrison",
        "Orc Avengers Garrison",
        "Blackshield Warriors Garrison",
        "Morgul Durburz Garrison",
        "Morannon Gathrak Garrison",
        "Black Uruks Garrison",
        "Black Uruk Halberd Garrison"
    ],
    ["timurids"] = [
        "Ents",
        "Beorning Bears",
        "Westron Ballista",
        "Westron Catapult",
        "Ent Catapult",
        "Wildmen Garrison Elite",
        "Bear Warriors Garrison",
        "Framsguard Dismounted Axemen Garrison",
        "Framsguard Dismounted Spearmen Garrison",
        "Human Boat"
    ],
    ["byzantium"] = [
        "Privateer Cavalry",
        "Westron Ballista",
        "Westron Catapult",
        "Northmen Garrison Elite",
        "Moriquendi Protectors Garrison",
        "Moriquendi Glademasters Garrison",
        "Moriquendi Sentinels Garrison",
        "Regent Axeguard Garrison",
        "Regent Bowguard Garrison",
        "Vintner-Court Knights Garrison",
        "Human Boat"
    ],
    ["spain"] = [
        "War Beasts of Harad",
        "Mumakil",
        "Harondor Mercenaries",
        "Farrhun Mercenaries",
        "Westron Ballista",
        "Westron Catapult",
        "Variag Swordsmen Garrison",
        "Southron Pikemen Garrison",
        "Serpent Bladesmen Garrison",
        "Southron Archers Garrison",
        "Human Boat",
        "Adunaim Boat"
    ],
    ["khand"] = [
        "Khand Heavy Crossbow Chariots",
        "Great Beasts",
        "Harondor Mercenaries",
        "Farrhun Mercenaries",
        "Westron Ballista",
        "Westron Catapult",
        "Dwarven Catapult",
        "Legionaries of Erebor Garrison",
        "Khand Elite Axemen Garrison",
        "Variag Bowmen Garrison",
        "Variag Swordsmen Garrison",
        "Temple Marksmen Garrison",
        "Temple Wards Garrison",
        "Human Boat"
    ],
    ["scotland"] = [
        "Westron Ballista",
        "Westron Catapult",
        "Northmen Garrison Elite",
        "Dalian Swordsmen Garrison",
        "Lake-town Pikemen Garrison",
        "Dalian Paladins Garrison",
        "Hearthguard Garrison",
        "Human Boat"
    ],
    ["milan"] = [
        "Lego Rohirrim",
        "Lego Spearmen",
        "Dwarven Travellers",
        "Westron Ballista",
        "Westron Catapult",
        "Northmen Garrison Elite",
        "Helm's Hammers Garrison",
        "Eored Footmen Garrison",
        "Eored Swordsmen Garrison",
        "Golden Hall Spearmen Garrison"
    ],
    ["sicily"] = [
        "Riders of the Green Hills2",
        "Anfalas Bodyguard2",
        "Lossarnach Household Guard2",
        "The White Company2",
        "Ringlo House Guards2",
        "Hobbit Infantry",
        "Bandobras Archers",
        "Watch Shirriffs",
        "Hobbit Ranchers",
        "Breeland Militia",
        "Ruffians",
        "Lumbermen",
        "Archer Militia",
        "Greenway Riders",
        "Merchant Militia",
        "Dunedain Volunteers",
        "Dunedain Wardens",
        "Tharbad Thieves",
        "Sworn Spearmen",
        "Sworn Defenders",
        "Watchmen Swordguard",
        "Watchmen Axeguard",
        "Cardolan Men-at-Arms",
        "Tharbad Tollkeepers",
        "Dunedain Rangers",
        "Watchmen Bowguard",
        "Sworn Archers",
        "Cardolan Sentinels",
        "Dunedain Scouts",
        "Sworn Horsemen",
        "Cardolan Riders",
        "Merchant Infantry",
        "Dunedain Armsmen",
        "Dunedain Blademasters",
        "Gate Keepers",
        "Dunedain Axemen",
        "Dismounted Fornost-Erain Knights",
        "Arthedain Pikemen",
        "Eriador Protectors",
        "Dunedain Troll Slayers",
        "Cardolan Sharpshooters",
        "Eriador Marksmen",
        "Fornost-Erain Knights",
        "Tharbad Riders",
        "tharbad_warhammer",
        "Arthedain Knights",
        "Sons of Numenor",
        "Annuminas Gateguards",
        "Dunedain Steelbowmen",
        "Arthedain Royal Guard",
        "Harondor Mercenaries",
        "Farrhun Mercenaries",
        "Gondor Ballista",
        "Gondor Catapult",
        "Gondor Trebuchet",
        "Eriador Trebuchet",
        "Gondor Garrison Elite",
        "Fountain Guard Garrison",
        "Lossarnach Axemen Garrison",
        "Guards of Osgiliath Garrison",
        "Osgiliath Veterans Garrison",
        "Raven Helms of Cair Andros Garrison",
        "Gondor Garrison Infantry",
        "Gondor Garrison Archers",
        "Gondor Boat",
        "Gondor Ship"
    ],
    ["saxons"] = [
        "Dunedain Bodyguard Twins",
        "Dunedain Wardens",
        "Dunedain Scouts",
        "Dunedain Troll Slayers",
        "Lindar Guards",
        "Lindar Mariners",
        "Lindon Longspears",
        "Lindar Bowmen",
        "Sindar Spearmen",
        "Sindar Axemen",
        "Sindar Archers",
        "Sindar Riders",
        "Heavy Falathrim Axeguard",
        "Heavy Falathrim Shipwrights",
        "Heavy Falathrim Archers",
        "Heavy Falathrim Skirmishers",
        "Mithlond Nobles",
        "Lindon Chariot",
        "Noldor Chariot",
        "Elven Ballista",
        "Elven Catapult",
        "Ent Catapult",
        "Sword Quendi Garrison",
        "Noldorin Veterans Garrison",
        "Elderinwe Tirno Garrison",
        "Heavy Falathrim Archers Garrison",
        "Mithlond Nobles Garrison",
        "Elven Ship",
        "Elven Boat"
    ],
    ["hungary"] = [
        "Merchant Cavalry",
        "War-goat Chariot",
        "Lindar Mariners",
        "Dwarven Ballista",
        "Ered Luin Ballista",
        "Ered Luin Catapult",
        "Dwarven Catapult",
        "Longbeard Swordsmen Garrison",
        "Longbeard Crossbows Garrison",
        "Gabilgathol Guard Garrison",
        "Khazad-dum Guardians Garrison",
        "Khazad-dum Reclaimers Garrison",
        "Human Boat",
        "Elven Boat"
    ],
    ["moors"] = [
        "Dale Cavalry",
        "War-goat Chariot",
        "Dwarven Ballista",
        "Dwarven Catapult",
        "Axeguard of Erebor Garrison",
        "Kings Warriors Garrison",
        "Iron Crossbowmen Garrison",
        "Legionaries of Erebor Garrison",
        "Khazad-dum Guardians Garrison"
    ],
    ["mongols"] = [
        "Ents",
        "Elven Ballista",
        "Elven Catapult",
        "Ent Catapult",
        "Elvenking's Swordguard Garrison",
        "Elvenkings Bowguard Garrison",
        "Hin e-Daur Garrison",
        "Elvenking's Palace Guard Garrison",
        "Galadhrim Archers Garrison",
        "Galadhrim Swordsmen Garrison",
        "Galadhrim Guards Garrison",
        "Human Boat"
    ],
    ["russia"] = [
        "Territorial Swordsmen",
        "Territorial Guardsmen",
        "Lebennin Marines",
        "Territorial Watchmen",
        "Territorial Cavalry",
        "Gondor Pikemen",
        "Gondor Infantry",
        "Gondor Spearmen",
        "Gondor Archers",
        "Lamedon Champions",
        "Lossarnach Household Guard",
        "Lossarnach Household Guard2",
        "Talon Knights",
        "Osgiliath Veterans",
        "Knights of the Silver Swan",
        "Breeland Militia",
        "Lumbermen",
        "Archer Militia",
        "Merchant Militia",
        "Dunedain Wardens",
        "Sworn Spearmen",
        "Sworn Defenders",
        "Watchmen Swordguard",
        "Watchmen Bowguard",
        "Dunedain Scouts",
        "Sworn Horsemen",
        "Gate Keepers",
        "Dunedain Axemen",

        "Peasant Militia",
        "Eorling Spearmen",
        "Eorling Archers",
        "Rohirrim",
        "Lego Rohirrim",
        "Lego Spearmen",
        "Rohirrim Archers",
        "Eored Swordsmen",
        "Eored Lancers",
        "Eored Skirmishers",
        "Rivermen",
        "Dalian Swordsmen",
        "Dalian Billmen",
        "Dalian Longbowmen",
        "Dale Cavalry",
        "Lake-town Pikemen",
        "Barding Marksmen",
        "Aihwothiuda Horseguards",
        "Thorn Bladesmen",
        "Thorn Guard",
        "Thorn Crossbowmen",
        "Thorn Patrolers",
        "Regent Spearguard",
        "Regent Bowguard",
        "Vintner-Court Knights",
        "Beorning Axemen",
        "Woodman Warriors",
        "Woodman Defenders",
        "Woodman Hunters",
        "Beorning Defenders",
        "Woodman Wardens",
        "Eotheod Horsemen",
        "Eotheod Archers",
        "Framsguard Dismounted Spearmen",
        "Angmarim Levies",
        "Rhudaur Savages",
        "Hillmen",
        "Rhudaur Huscarles",
        "Rhudaur Bodyguards",
        "Rhudaur Spearmen",
        "Angmarim Warriors",
        "Angmarim Pikes",
        "Morholt Chosen",
        "Dreadguard",
        "Darkblades",
        "Clan Axemen",
        "Clan Spearmen",
        "Frekkalingir Hill-Riders",
        "Dunhird Berserkers",
        "Frekkalingir Harriers",
        "Warband Blades",
        "Dunhird Slayers",
        "Warband Sentries",
        "Wulfguard Axemen",
        "Faolan Borderguard",
        "Mordag Fishermen",
        "Keefei Huntsmen",
        "Liadan Billmen",
        "Faolan Warriors",
        "Fylani Herders",
        "Mochaini Ambaxtoi",
        "Enedwaith Guardsmen",
        "Haradrim Archers",
        "Southron Warband",
        "Southron Pikemen",
        "Southron Lancers",
        "Muhad Tribesmen",
        "Hasharii Blades",
        "Serpent Bladesmen",
        "Hasharii Shadows",
        "Steppe Tribesmen",
        "Nomad Axemen",
        "Marauders",
        "Khandish Raiders",
        "Nomad Horsemen",
        "Variag Bowmen",
        "Variag Horse Archers",
        "Rhunnic Spears",
        "Rhunnic Warriors",
        "Fang-Guard",
        "Rhunnic Bowmen",
        "Claw-Guard",
        "Fire-Guard",
        "Loke-Rim Poleaxemen",
        "Loke-Rim Pikemen",
        "Loke-Rim Swordsmen",
        "Loke-Rim Spearmen",
        "Loke-Rim Archers",
        "Loke-Rim Cavalry",
        "Loke-Scion Rim",
        "Loke-Nar Rim",
        "Suriut Chariots",
        "Dragon-Wrath Shields",
        "Dragon-Wrath Swiftblades",
        "Dragons Wrath Guardians",
        "Dragon-Wrath Kataphracts",
        "Merchant Cavalry",
        "Greenway Spearmen",
        "Journeymen",
        "Saralainn Mercenaries",
        "Harondor Mercenaries",
        "Farrhun Mercenaries",
        "Westron Ballista",
        "Westron Catapult",
        "Gondor Trebuchet",
        "Watchmen Swordguard Garrison",
        "Watchmen Bowguard Garrison",
        "Greenway Spearmen Garrison",
        "Journeymen Garrison",
        "Royal Legion of Armenelos Garrison",
        "Liadan Billmen Garrison",
        "Warband Blades Garrison",
        "Warband Sentries Garrison",
        "Wulfguard Axemen Garrison",
        "Iron Crown Warriors Garrison",
        "Loke-Rim Pikemen Garrison",
        "Dragon-Wrath Shields Garrison",
        "Loke-Rim Archers Garrison",
        "Regent Bowguard Garrison",
        "Vintner-Court Knights Garrison",
        "Dalian Swordsmen Garrison",
        "Lake-town Pikemen Garrison",
        "Eored Swordsmen Garrison",
        "Dunedain Axemen Garrison",
        "Variag Bowmen Garrison",
        "Numenorean Marksmen Garrison",
        "Numenorean Cohort Garrison",
        "Southron Pikemen Garrison",
        "Serpent Bladesmen Garrison",
        "Fountain Guard Garrison",
        "Raven Helms of Cair Andros Garrison",
        "Gondor Garrison Infantry",
        "Gondor Garrison Archers",
        "Adunaim Boat",
        "Adunaim Ship"
    ],
    ["venice"] = [
        "Suriut Chariots",
        "Khamuls Shadowguard",
        "Khamuls Shadow Rangers",
        "Khamul's Chosen",
        "Khamuls Shadowknights",
        "Farrhun Mercenaries",
        "Rhunnic Catapult",
        "Rhunnic Ballista",
        "Dragons Breath",
        "Loke-Rim Pikemen Garrison",
        "Loke-Rim Macemen Garrison",
        "Dragon-Wrath Shields Garrison",
        "Loke-Rim Archers Garrison",
        "Khamuls Shadow Rangers Garrison",
        "Khamul's Chosen Garrison",
        "Variag Swordsmen Garrison",
        "Human Boat"
    ],
    ["aztecs"] = [
        "Rohirrim",
        "Lego Rohirrim",
        "Rohirrim Archers",
        "Lurtz's Hunting Pack",
        "Uruk-hai Raiders",
        "Uruk-hai Archers",
        "Berserkers",
        "Lego Uruk-hai Infantry",
        "Lego Berserkers",
        "Uruk-hai Infantry",
        "Uruk-hai Crossbow",
        "Saralainn Mercenaries",
        "Westron Ballista",
        "Westron Catapult",
        "Wildmen Garrison Elite",
        "Warband Blades Garrison",
        "Warband Sentries Garrison",
        "Wulfguard Axemen Garrison",
        "Human Boat"
    ],
}
