::EUR.eurSaveLoadValues <- function(bool) {
    if (bool) {
        ::EUR.eurEventsData = {
            UNIT_FILTER = ::EUR.UNIT_FILTER,
            UNIT_FILTER_notif = ::EUR.UNIT_FILTER_notif,
            faction_revival = ::EUR.faction_revival,
            faction_disposition = ::EUR.faction_disposition,
            UNIT_UPGRADES = ::EUR.UNIT_UPGRADES,
            misc_options = ::EUR.misc_options,
            GARRISON_TRACK = ::EUR.GARRISON_TRACK,
            gen_set = ::EUR.gen_set,
            strat_cas_setts = ::EUR.strat_cas_setts,
            custom_maps = ::EUR.custom_maps,
            bgunlock_units_list = ::EUR.bgunlock_units_list,
            game_options = ::EUR.game_options,
            anorien_swap = ::EUR.anorien_swap,
            watchtower_range = ::EUR.watchtower_range,
            options_general_large_army = ::EUR.options_general_large_army,
            extents_entries = ::EUR.extents_entries,
            options_replen_costs = ::EUR.options_replen_costs,
            replen_cost_multi = ::EUR.replen_cost_multi,
            list_edu_table_default = ::EUR.list_edu_table_default,
            list_edu_table = ::EUR.list_edu_table,
            restricted_upgrades = ::EUR.restricted_upgrades,
            ai_unit_upgrades = ::EUR.ai_unit_upgrades,
            show_adv_replen = ::EUR.show_adv_replen,
            replen_values = ::EUR.replen_values,
            bg_t2_rank = ::EUR.bg_t2_rank,
            bg_t3_rank = ::EUR.bg_t3_rank,
            show_gen_unit_card = ::EUR.show_gen_unit_card,
            set_mods = ::EUR.set_mods,
            personal_guard_limit = ::EUR.personal_guard_limit,
            modifier_config = ::EUR.modifier_config,
            waystation_bonus = ::EUR.waystation_bonus,
            gen_units_list = ::EUR.gen_units_list,
            options_evolvingnames = ::EUR.options_evolvingnames,
            eregion_spawned = ::EUR.eregion_spawned,
            options_extrabu = ::EUR.options_extrabu,
            add_setts = ::EUR.add_setts,
            EDUOFFET_SETT_VARS = ::EUR.EDUOFFET_SETT_VARS,
            EDUOFFET_VARS = ::EUR.EDUOFFET_VARS,
            EDUOFFET_VARS_LEG = ::EUR.EDUOFFET_VARS_LEG,
            eregion_realms_start = ::EUR.eregion_realms_start,
            eregion_realms_sett_taken = ::EUR.eregion_realms_sett_taken,
            eregion_maernil_choice = ::EUR.eregion_maernil_choice,
            eur_eregion_active = ::EUR.eur_eregion_active,
            text_colour = ::EUR.text_colour,
            options_no_free_upkeep = ::EUR.options_no_free_upkeep,
            build_forts = ::EUR.build_forts,
            noldor_ui_updated = ::EUR.noldor_ui_updated,
            towers_already = ::EUR.towers_already,
            options_extraBGunits = ::EUR.options_extraBGunits,
            PURSE_MODIFIED = ::EUR.PURSE_MODIFIED,
            options_legendary = ::EUR.options_legendary,
            global_recruit_limit = ::EUR.global_recruit_limit,
            global_recruits = ::EUR.global_recruits,
            ship_1_active = ::EUR.ship_1_active,
            ship_2_active = ::EUR.ship_2_active,
            ship_3_active = ::EUR.ship_3_active,
            ship_4_active = ::EUR.ship_4_active,
            king_1_active = ::EUR.king_1_active,
            king_2_active = ::EUR.king_2_active,
            king_3_active = ::EUR.king_3_active,
            stew_1_active = ::EUR.stew_1_active,
            stew_2_active = ::EUR.stew_2_active,
            stew_3_active = ::EUR.stew_3_active,
            options_gennotif = ::EUR.options_gennotif,
            dwarven_0_bu_added = ::EUR.dwarven_0_bu_added,
            dwarven_0_count = ::EUR.dwarven_0_count,
            anor_target_faction = ::EUR.anor_target_faction,
            anorTurnsRemain = ::EUR.anorTurnsRemain,
            tempmengoodTarget = ::EUR.tempmengoodTarget,
            mengood_0_sett = ::EUR.mengood_0_sett,
            mengoodTurnsRemain = ::EUR.mengoodTurnsRemain,
            eyeTarget = ::EUR.eyeTarget,
            bg_min_size_multi = ::EUR.bg_min_size_multi,
            merge_turn_multi = ::EUR.merge_turn_multi,
            bg_swap_cooldown = ::EUR.bg_swap_cooldown,
            options_hardcore = ::EUR.options_hardcore,
            options_gen_upgrades = ::EUR.options_gen_upgrades,
            options_gen_bg_size = ::EUR.options_gen_bg_size,
            options_first_run = ::EUR.options_first_run,
            replen_low = ::EUR.replen_low,
            replen_mid = ::EUR.replen_mid,
            replen_high = ::EUR.replen_high,
            replen_text = ::EUR.replen_text,
            replen_always = ::EUR.replen_always,
            poe_turns_min = ::EUR.poe_turns_min,
            poe_turns_max = ::EUR.poe_turns_max,
            random_poe = ::EUR.random_poe,
            options_unit_upgrades = ::EUR.options_unit_upgrades,
            unit_upgrades_multi = ::EUR.unit_upgrades_multi,
            options_pre_battle = ::EUR.options_pre_battle,
            options_addspoils = ::EUR.options_addspoils,
            options_replen_beast = ::EUR.options_replen_beast,
            replen_randmax = ::EUR.replen_randmax,
            replen_multi = ::EUR.replen_multi,
            replen_beast_value = ::EUR.replen_beast_value,
            char_unlocks = ::EUR.char_unlocks,
            font_choice = ::EUR.font_choice,
            current_heir_check = ::EUR.current_heir_check,
            temp_units = ::EUR.temp_units,
            temp_unit_nu = ::EUR.temp_unit_nu,
            labtrait_units_list = ::EUR.labtrait_units_list,
            persistent_gen_list = ::EUR.persistent_gen_list,
            persistent_gen_list_reset = ::EUR.persistent_gen_list_reset,
            options_replen = ::EUR.options_replen,
            show_options_window = ::EUR.show_options_window,
            options_poe = ::EUR.options_poe,
            options_merge = ::EUR.options_merge,
            options_sort = ::EUR.options_sort,
            options_prepost_save = ::EUR.options_prepost_save,
            sort_order = ::EUR.sort_order,

            eur_already_saved = ::EUR.eur_already_saved,

            total_spoils_loot = ::EUR.total_spoils_loot,

            battles_lost = ::EUR.battles_lost,
            losses_upkeep = ::EUR.losses_upkeep,
            total_losses_upkeep = ::EUR.total_losses_upkeep,
            eur_spawned_characters = ::EUR.eur_spawned_characters,

            tempmirrorTarget = ::EUR.tempmirrorTarget,
            mirrorTarget = ::EUR.mirrorTarget,
            mirrorTurnsRemain = ::EUR.mirrorTurnsRemain,

            traitToAdd = ::EUR.traitToAdd,
            traitTurnsRemain = ::EUR.traitTurnsRemain,

            fert_level = ::EUR.fert_level,
            modify_growth = ::EUR.modify_growth,
            growthTurnsRemain = ::EUR.growthTurnsRemain,
            replen_bonus = ::EUR.replen_bonus,

            block_poe_turns = ::EUR.block_poe_turns,

            eur_event_active = ::EUR.eur_event_active,
            eur_event_activelen = ::EUR.eur_event_activelen,

            eur_event_min_cooldown = ::EUR.eur_event_min_cooldown,
            event_number = ::EUR.event_number,
            poe_end_condition = ::EUR.poe_end_condition,
            edumodTurnsRemain = ::EUR.edumodTurnsRemain,
            edumodActive = ::EUR.edumodActive,
            tulkasTurnsRemain = ::EUR.tulkasTurnsRemain,
            tulkasActive = ::EUR.tulkasActive,
            lindon_0_count = ::EUR.lindon_0_count,
        }
        ::persistent.eur <- ::EUR.eurEventsData

    } else {

        if (!("eur" in ::persistent)) { return }
        ::EUR.eurEventsData = ::persistent.eur

        local varsToLoad = [
            ["UNIT_FILTER_notif"],
            ["UNIT_FILTER"],
            ["faction_revival"],
            ["faction_disposition"],
            ["UNIT_UPGRADES", ::EUR.UNIT_UPGRADES_default],   // has a defaultVal fallback
            ["misc_options"],
            ["GARRISON_TRACK"],
            ["gen_set"],
            ["strat_cas_setts"],
            ["game_options"],
            ["bgunlock_units_list"],
            ["custom_maps"],
            ["anorien_swap"],
            ["watchtower_range"],
            ["options_general_large_army"],
            ["options_replen_costs"],
            ["replen_cost_multi"],
            ["list_edu_table_default"],
            ["ai_unit_upgrades"],
            ["list_edu_table"],
            ["show_adv_replen"],
            ["replen_values"],
            ["bg_t2_rank"],
            ["bg_t3_rank"],
            ["show_gen_unit_card"],
            ["set_mods"],
            ["personal_guard_limit"],
            ["modifier_config"],
            ["waystation_bonus"],
            ["gen_units_list", ::EUR.gen_units_list_default],
            ["options_evolvingnames"],
            ["eregion_spawned"],
            ["options_extrabu"],
            ["add_setts"],
            ["EDUOFFET_SETT_VARS"],
            ["EDUOFFET_VARS"],
            ["EDUOFFET_VARS_LEG"],
            ["eregion_realms_start"],
            ["eregion_realms_sett_taken"],
            ["eregion_maernil_choice"],
            ["eur_eregion_active"],
            ["text_colour"],
            ["options_no_free_upkeep"],
            ["build_forts"],
            ["noldor_ui_updated"],
            ["towers_already"],
            ["options_extraBGunits"],
            ["PURSE_MODIFIED"],
            ["options_legendary"],
            ["global_recruit_limit"],
            ["global_recruits"],
            ["ship_1_active"],
            ["ship_2_active"],
            ["ship_3_active"],
            ["ship_4_active"],
            ["king_1_active"],
            ["king_2_active"],
            ["king_3_active"],
            ["stew_1_active"],
            ["stew_2_active"],
            ["stew_3_active"],
            ["options_gennotif"],
            ["dwarven_0_bu_added"],
            ["dwarven_0_count"],
            ["anor_target_faction"],
            ["anorTurnsRemain"],
            ["tempmengoodTarget"],
            ["mengood_0_sett"],
            ["mengoodTurnsRemain"],
            ["eyeTarget"],
            ["bg_min_size_multi"],
            ["merge_turn_multi"],
            ["bg_swap_cooldown"],
            ["options_hardcore"],
            ["options_gen_upgrades"],
            ["options_gen_bg_size"],
            ["options_first_run"],
            ["replen_low"],
            ["replen_mid"],
            ["replen_high"],
            ["replen_text"],
            ["replen_always"],
            ["poe_turns_min"],
            ["poe_turns_max"],
            ["random_poe"],
            ["options_unit_upgrades"],
            ["unit_upgrades_multi"],
            ["options_pre_battle"],
            ["options_addspoils"],
            ["options_replen_beast"],
            ["replen_randmax"],
            ["replen_multi"],
            ["replen_beast_value"],
            ["char_unlocks"],
            ["font_choice"],
            ["current_heir_check"],
            ["temp_units"],
            ["temp_unit_nu"],
            ["labtrait_units_list"],
            ["persistent_gen_list"],
            ["persistent_gen_list_reset"],
            ["options_replen"],
            ["show_options_window"],
            ["options_poe"],
            ["options_merge"],
            ["options_sort"],
            ["options_prepost_save"],
            ["sort_order"],
            ["eur_already_saved"],
            ["total_spoils_loot"],
            ["battles_lost"],
            ["losses_upkeep"],
            ["total_losses_upkeep"],
            ["eur_spawned_characters"],
            ["tempmirrorTarget"],
            ["mirrorTarget"],
            ["mirrorTurnsRemain"],
            ["traitToAdd"],
            ["traitTurnsRemain"],
            ["fert_level"],
            ["modify_growth"],
            ["growthTurnsRemain"],
            ["replen_bonus"],
            ["block_poe_turns"],
            ["eur_event_active"],
            ["eur_event_activelen"],
            ["eur_event_min_cooldown"],
            ["event_number"],
            ["poe_end_condition"],
            ["edumodTurnsRemain"],
            ["edumodActive"],
            ["tulkasTurnsRemain"],
            ["tulkasActive"],
            ["lindon_0_count"],
        ]

        // Keys where missing table entries should NOT be filled from defaults
        local noMergeFill = {
            UNIT_UPGRADES  = true,
            gen_units_list = true,
        }

        local root = ::EUR
        foreach (entry in varsToLoad) {
            local key     = entry[0]
            local defaultVal = (entry.len() > 1) ? entry[1] : null

            if (::EUR.to_log) {
                println("EUR SCRIPT: " + key)
            }

            local loaded = (key in ::EUR.eurEventsData) ? ::EUR.eurEventsData[key] : null

            if (loaded != null) {
                if (typeof(loaded) == "table" && !(key in noMergeFill)) {
                    if (defaultVal != null && typeof(defaultVal) == "table") {
                        foreach (dk, dv in defaultVal) {
                            if (!(dk in loaded)) {
                                loaded[dk] <- dv
                            }
                        }
                    }
                }
                root[key] <- loaded
            } else if (defaultVal != null) {
                root[key] <- defaultVal
            }
        }

    }

}
