// eurText - dumped string tables for the EUR scripts. Sectioned by source; more sections will be
// appended here as other files' strings are migrated. Strings are Squirrel verbatim (@"..."),
// preserved byte-for-byte from the source (only interior double-quotes are doubled per @" rules).

// ==============================================================================================
// Eregion / Kingdom of Noldor / Kingdom of Eregion story (from eurConfed.lua)
// ==============================================================================================

::EUR.REACHED_OST_IN_EDHIL_BODY <- @"While scouring the lands of Eregion in search of our foes, the most far-sighted of our scouts have returned. They bring tidings both bitter and stirring. The broken Jewel of Elvendom in the West, Ost-in-Edhil, the glittering seat of Lord Celebrimbor himself, has been rediscovered. It lies to the south, where the Glanduin's silver waters bleed from the bitter roots of the Misty Mountains, a place long shrouded in the mists of memory and mourning.

This hallowed ground where works to rival the palantíri were conceived, and the very air hummed with the craft-song of the Gwaith-i-Mirdain, bears fresh wounds. Hordes of Vile goblins now defile the sanctity of those graves. They nest like maggots in the carcass of our ancient glory. They scour murals depicting Feanor's most sacred of craft, the forging of the Silmarils, they desecrate the Halls of the Gwaith-i-Mirdain with foul runes, and pollute the forges where Three Rings were forged with their waste. The very stones weep to bear their footfalls.

The War Council's voice rings clear as a forge-::EUR.hammer: We shall redeem this sin against our blood! Let the Wardens of Imladris march at once to scour Ost-in-Edhil of their filth! We must set forth on a pilgrimage of purification, and only when these defilers are cast screaming into the abyss can we begin the long labor of resurrection. To relight the forgefires, rebuild the Dome of Telperion, and restore the forge-halls where Celebrimbor walked. Let the City of Jewel-Smiths rise... not as a ghost, but as a Star, a testament to the Ñoldor's resilience against the Long Shadow in the East."
::EUR.REACHED_OST_IN_EDHIL_TITLE <- @"Ancient Ruin Scouted"

::EUR.REACHED_OST_EN_NOLDOR_BODY <- @"While ranging the wild reaches of Western Eriador for traces of our enemy's advance, our swiftest scouts have made a discovery that stirs both hope and rage: the crumbling bones of Ost-in-Ñoldor, the ancient Fortress now known only as Amon Luinë, lies still to the South of the Havens, like a shard from a long forgotten crown. This sacred ground, where our ancestors first rekindled the light of the Elvendom in Middle-earth, has been defiled. 

Vile goblins now prowl its shattered colonnades, their crude forge-fires have blackened hallowed stones, and their filth befouled chambers that once echoed with our sacred hymns. They gleefully desecrated altars to the Valar, and defaced beautiful reliefs of the Two Trees with their foul sigils. The Council of the Wise bristles at this report, and are galvanized to urge immediate action. 

We must dispatch a force to scour 'Amon Luinë' of this blight! This is no mere conquest... it is our most sacred duty to wrest our birthright from the claws of the Enemy. Only once these defilers have been cast into the abyss can we begin the long labor of its restoration. In time, Ost-in-Ñoldor shall stand as a restored beacon of our people's beauty and tenacity."
::EUR.REACHED_OST_EN_NOLDOR_TITLE <- @"Ancient Ruin Scouted"

//CAPTURE SETTLEMENT
::EUR.CAPTURED_OST_IN_EDHIL_BODY <- @"As our forces carried out the reclamation of Ost-in-Edhil, they discovered an ancient chamber. Formerly one of the Gwaith-i-Mirdain's vaults, it is now home to an emaciated Ñoldor prisoner clinging to life. To our astonishment and joy, the prisoner is discovered to be none other than High Prince Maernil, last scion of the House of Feanor. He was mourned as ash upon the wind in the days after Eregion burned and passed into memory; his name was among those war-cries calling for vengeance. He was not found amidst glory, as he should have been, but as a broken doll in a cairn of stone. His liberation was swift, and gentle where his captors' had been cruel; Now, hallowed waters from the Celebrant pass his lips, and elven-healers sing songs of awakening and restoration.

He will be borne from that ruin upon a litter of woven mallorn-boughs, guarded by oathsworn blades, and carried not to a throne, but to the Last Homely House. There, Lord Elrond Half-Elven will tend to him with the gentlest hands of all the Wise. His voice will be heard, and call Prince Maernil back to the Light."
::EUR.CAPTURED_OST_IN_EDHIL_TITLE <- @"The Last Heir of Feanor"

::EUR.CAPTURED_OST_EN_NOLDOR_BODY <- @"As our warriors drove deeper into the reclaimed halls of Ost-in-Ñoldor, as they cleansed the shadows where Goblin filth swarmed like maggots on a wound, they discovered and breached a sealed vault. Once a sanctum for treasures forged in memory of the Light of the Two Trees it now stank as a tomb of rancid, stagnant, air. Amidst the shattered reliquaries, a skeletal figure stirs. Clad in tattered rags, that even now recall the majesty of a prince's garb, starved nearly to the limit of his flesh, and yet clinging to life with indomitable will, hangs a Ñoldor captive. At first, he was believed to be a ghost, doomed to persist in chains by the machinations of the Enemy for Ages uncounted.

We know now that he is High Prince Maernil, the last scion of the House of Feanor. He was mourned as lost when Eregion burned and passed into memory; his name was among those war-cries calling for vengeance, and his deeds recalled among the heroes of the Second Age. He was found, not amidst glory, but as a broken husk persisting in a grave of stone. His liberation was swift and gentle. He was borne from the lair of his cruel jailors upon a litter of woven mallorn boughs. Even now, hallowed waters from the havens pass his lips, and elven-healers sing songs of awakening and restoration. Yet, he is still in grave health, and will remain so until he is tended to by one of the Wise.

He shall be carried to the Grey Havens, to the very heart of Mithlond, where the sea-wind carries the scent of Valinor. There, beneath Lord Círdan's ancient and diligent gaze, his shattered body and fierce, wounded, spirit will find solace. His path no longer leads to crowns carved of conflict, but westward, toward the Undying Lands. The Prince returns, not as a conqueror reborn, but as a wounded spirit seeking the long-denied grace of the setting sun. When he is well, he shall be allowed to board a ship, that he may find peace at last, beyond the circles of the world's sorrow."
::EUR.CAPTURED_OST_EN_NOLDOR_TITLE <- @"The Lost Heir"

//GOBLIN INVASION
::EUR.I_EREGION_GOBLIN_INVASION_START_BODY <- @"Scouts return from the shadowed valleys beneath the Hithaeglir, their faces pale as moonstone. They bring grim tidings: the Doors of Durin, the long silent funerary stones that remember Khazad-dûm at its height, when Elf and Dwarf were friends, stir with the passage of foul creatures. By daylight, the stone remains shut, a tomb's mouth clenched against the caress of the Sun. Yet, as twilight bleeds into night... the Doors open. Detachments of Goblins, rank upon rank, sharpened blades glinting in the dim flame of their malice, pour forth like pus from a festering wound. Alongside them, fouler shapes prowl, things that shun the moon's gaze, whose footsteps leave furrows in summer grass, whose bellows fray the edges of mortal courage. The filth of the deep places gathers along our borders. Worst of all, a messenger comes from Lórien, bearing Galadriel's seal, with a message that chills the blood. ‘A Shadow moves in the uttermost deeps of Moria. Something ancient, fouler than any Goblin's craft. Something that drowns light in Shadow and Flame. It gathers its strength in the black pools beneath the roots of Caradhras, and stirs in answer to your trumpets' song.' 
Let every blade in Imladris be honed, and those who are capable girded in the raiment of war. The Council speaks with one voice: This is no raid, but the mustering of an invasion. Should Moria's legions spill unchecked into Eriador, they will drown all the land in shadow, shatter the peace of the Last Homely House, and grind the last havens of the Eldar to dust. We do not prepare for a battle, but for a war against our very annihilation. The Enemy marches, and the twilight over Middle-earth deepens."
::EUR.I_EREGION_GOBLIN_INVASION_START_TITLE <- @"Dark Clouds Gather"

::EUR.I_EREGION_GOBLIN_INVASION_HALFWAY_BODY <- @"Our scouts come more frequently now, many driven to haste by fear. Their reports confirm our darkest fears... The Doors of Durin now stand as an open wound, vomiting forth goblin warbands in numbers unseen since the Burning of Eregion. Their long fractured tribes now march under a single fell banner, united not by the ambition and malice of their race, but by raw terror. They flee something that stirs in the deeps, that drives them before it like leaves in a hurricane.

Even now, they flood the western passes as a jeering, screeching tide; that sets the Foothills ablaze with their passage. Those few of the free peoples, who dared scratch lives from the stony slopes, are overrun. Their homes are reduced to charred bones, and their farms to blood-slicked earth. Where silence once dwelt, long and patient, the mountains now echo with the scrape of the Goblins' crude steel, their guttural war-cries thick with dread, and accompanied by the howling of Wargs starved for elf-flesh. Worse. All the breeds of Troll-Kin that have terrorized the Free Peoples from the Ettenmoors to the Fords of Isen follow them, carrying the stink of yawning graves, and we fear fouler things may yet follow. Our armies must stand ready, for a Long Night threatens to descend, and Middle-earth's very fate may rest the edge of our blades."
::EUR.I_EREGION_GOBLIN_INVASION_HALFWAY_TITLE <- @"The Shadow Flows West"

::EUR.I_EREGION_GOBLIN_INVASION_ARRIVE_BODY <- @"Like the great rumble of an avalanche, the goblins descend upon our lands in filth and fury. The lands from the Glanduin to the Bruinen are swarmed in their camps, crowned with crude banners that spell doom from every horizon. The Villages burn, wells are poisoned, and now our warriors must stand as the last line between civilization and ruin. As was said by Húrin in days of old, ""Aurë entuluva!"" Day shall come again! The battle for Imladris has begun... Stand firm! For the enemy will show no mercy."
::EUR.I_EREGION_GOBLIN_INVASION_ARRIVE_TITLE <- @"Hidden Valley Despoiled"

::EUR.I_EREGION_REALMS_START_BODY <- @"The invasion has been repelled! Through valorous sacrifice, and unyielding resolve, we have cast the goblins back into the abyss from whence they came. Their warbands are reduced to piled funeral pyres, their chieftains slain, and their dark ambitions shredded by our glittering blades. The scars of this war may remain, but for today, we standd victorious. But do not let this victory dull your blades, for the deeps of the Misty Mountains still snarl with a far more ancient malice. Something stirs beneath Moria, and should it be allowed to awaken, the horror it unleashes may eclipse even this war. Remain vigilant.

(Expand your territory and await Prince Maernil's recovery to progress the story)"
::EUR.I_EREGION_REALMS_START_TITLE <- @"Goblin Invasion Thwarted"

::EUR.L_EREGION_GOBLIN_INVASION_START_BODY <- @"Scouts report that the hordes of the Blue Crag have been seen gathering their strength. This Enemy’s strength is great, with teeming packs of goblins and wargs, and they are led by the most cruellest and most sadistic of the crag’s Uruk-kin. Whether they mean to assault the Havens, or to strike East toward the fallen kingdoms of Cardolan and Arthedain is not yet known. Already, warnings have been dispatched to our allies in Imladris, and the Rangers of the North, but if the Enemy chooses to strike for our own lands, they must find us well prepared. Gather our strength, for failure would spell the end of Elvendom in the West."
::EUR.L_EREGION_GOBLIN_INVASION_START_TITLE <- @"Ill Tidings from the Blue Mountains"

::EUR.L_EREGION_GOBLIN_INVASION_HALFWAY_BODY <- @"The Blue Crag's armies move for Mithlond. Their war drums were first heard at sundown not one week ago. Their baying cries, like rabid beasts, echo through the valleys with sickening delight. Our outriders report growing numbers of the Crag’s goblin hosts, augmented by savage engines of war, and a fell chieftain at their head. Worse, they have spread throughout the lowlands, pillaging and killing with abandon. It is unavoidable, this host is too great to face in the field. The foothills must be forsaken, and our border guards withdrawn to the muster grounds, for we cannot risk the Havens being taken by this horde of corruption and death. We fear that they soon shall unleash a war not seen in these lands since the Breaking of Beleriand; and if we should fail, there will be no ships to carry the Elves journeying into the uttermost West. It is for them that must make our stand."
::EUR.L_EREGION_GOBLIN_INVASION_HALFWAY_TITLE <- @"Drums of War"

::EUR.L_EREGION_GOBLIN_INVASION_ARRIVE_BODY <- @"The wave of the enemy crests. Like a tide of stinking flesh and rotten souls, the Blue Crag's mightiest have poured forth to assail us. The farmlands burn, those men among us too stubborn to flee have either gone unnoticed, or passed beyond our sight. We have run out of time, and now Mithlond is beset by their onslaught. The Goblins have been spied testing their brutal siege engines on farmhouses and captured farmers, reveling in the cruelty as a sick form of 'revenge' for our campaigns into their heartlands. Smoke rises from dozens of burning homesteads, and the baying howls of the Goblin warhost is a deafening wail on the wind. We must not yield any more ground. The line has been drawn, and to lose it may mean ruin for all!"
::EUR.L_EREGION_GOBLIN_INVASION_ARRIVE_TITLE <- @"An Avalanche of Cruelty"

::EUR.L_EREGION_REALMS_START_BODY <- @"Utúlie'n aurë! We have held Mithlond against the tide. Their banners are trampled into the dust, their forces scattered like water crashing over stones. The Goblins, so recently howling and baying in sadistic glee, now flee our lands with their whips between their legs! Yet, the danger is not yet over, for they may yet have the strength to regroup and revenge themselves upon us. For now, at the least, their schemes are undone and we have earned precious time to rest. Though our walls are scarred by the engines of war, our people stand triumphant, even as we grieve those valiant lives given in our defense.Yet, this is no time for complacency and festivals of victory, for the roots of the Blue Mountains echo with foreboding malice. Lord Círdan’s sight, among the keenest of Elvenkind, perceives an ancient terror whose malice grows toward a terrible crescendo. We fear that this horde was but the leading edge of a far more terrible storm. If that is true, then we must be vigilant for the true storm yet to come, for the hills may soon be soaked crimson from the price of our defiance.

(Expand your territory and await Prince Maernil's recovery to progress the story)"
::EUR.L_EREGION_REALMS_START_TITLE <- @"The Storm Passes"

//REBELLION
::EUR.EREGION_MAERNIL_RECOVER_BODY <- @"After a long recovery, Prince Maernil has emerged with his health restored, and his spirit ablaze. Yet, those who know the Prince best sense that he carries with him a new weight. His resolve has been hardened to flint, and his eyes smolder with a fierce, forgotten flame. The past hangs upon him, as an invisible weight like a thorned chain, and through the halls of the Wise, whispers persist not of recovery, but of a looming reckoning and a self-appointed destiny that will demand fulfillment."
::EUR.EREGION_MAERNIL_RECOVER_TITLE <- @"Prince Maernil emerges"

::EUR.EREGION_REBELLION_START_BODY <- @"Whispers have turned to rumour, that Prince Maernil secretly courts our war councils, vigorously advocating his ambition to restore the Kingdom of Eregion. Alarmed by his accelerating influence and the unsettling, seductive power of his agenda, Círdan the Shipwright and Elrond Half-Elven maintain a fierce, watchful eye on the High Prince, and his every move only deepens that terrible apprehension."
::EUR.EREGION_REBELLION_START_TITLE <- @"Shadow of Wrathful Ambition"

::EUR.EREGION_REBELLION_CHOICE_BODY <- @"It is as we feared... The schism has deepened, and there is now talk of open war! Voices cry out against our 'stagnation' and the gradual decline of our people. They wish now to forge a new kingdom, one they say shall be as resplendent as the halls of lost Gondolin. Their detractors speak only of ruin, carrying the memory of ambition's bitter fruit. The paths before us now, are stark, and bitterly opposed. Shall we grasp the torch, and rekindle the ancient fire? Or, shall we accept our long decline, usher in the Age of Men, and pass into the silent archives of time's memory?"
::EUR.EREGION_REBELLION_CHOICE_TITLE <- @"Strife in the Halls of the Wise"

::EUR.EREGION_REBELLION_CHOICE_R_BODY <- @"Like fell heralds of the First Age, the House of Fëanor has clawed from the ash heap of history's unyielding pyre. Propelled by a will as unyielding as the chains that bound Sauron's master, Maernil's followers are bound by new and accursed Oaths; and those chains are hotter than dragon's flame. They have claimed Eregion's corpse as their rightful inheritance, and in their eyes, blade and sorcery are the instruments of righteous vengeance, consecrated by their wrath. They intend to reclaim what was ‘stolen' from them. They say that the Passing of the Elves is a betrayal of the Ñoldor's fierce essence, and the blood they shed defending the world from the Servants of Shadow.

Maernil's host marches not for wealth or land, but under the grim weight of oaths consecrated in blood. Their banners, shrouds echoing the crimson flames that devoured Teleri sails before a Sun shone over Middle-Earth. To them, mercy is a foreign ideal, and their purpose is to scour all their enemies from the Earth… rick, cot, and tree. They crusade for the vindication of Feanor's fire, and to settle accounts written by the lashes of the Balrogs millennia ago. They will not stop until every stronghold bears a funeral's pyre, and histories of their foes are written in ash carried by the wind. "
::EUR.EREGION_REBELLION_CHOICE_R_TITLE <- @"The Oath of Feanor"

::EUR.EREGION_REBELLION_CHOICE_A_BODY <- @"Those among the Elves who desired the Dominion of Elvendom raised their voices, and shed blood in oaths to High Prince Maernil. They do not call him simply the Prince of the Elves, but the Heir of Feanor, and the rightful High King! Those few who lived to see Feanor in days of old say the same fire burned in his eyes, that he has been sent back to them from the Halls of Mandos; to cleanse Middle-Earth of all Darkness. With grim resolve, they gird themselves in the raiment of war, and demand that all Elvendom follow suit…
Or be swept aside."
::EUR.EREGION_REBELLION_CHOICE_A_TITLE <- @"Rise of the Accursed"

//KINGDOM OF Ñoldor
::EUR.KON_KINSLAYING_BODY <- @"Prince Maernil's ambition, curdled by his long torture at the Goblins' hands, has turned to utter madness. His most zealous followers march alongside him to seize Ost-in-Edhil, and proclaim any Elf in his path a traitor to be destroyed. Their Blades gleam with fell light, and their banners are dyed in the shades of their murdered kinsmen… the grim hues of vengeance. The Elven Kingdoms are fractured by this self-inflicted blow. Maernil advances, his armies carve a bloody path toward destiny, heedless of the bitter cost, and those he must sacrifice for the kingdom he seeks to reclaim. 

The Fourth Kinslaying has begun."
::EUR.KON_KINSLAYING_TITLE <- @"The Fourth Kinslaying"

::EUR.KON_EREGION_DESTROY_BODY <- @"Eregion is ruined. Its halls are once again deserted, and smolder with the remnants of the defenders' wrath. Its forges are cold, and dead. Its people are scattered remnants, adrift on a sea of sorrow. From the ashes of ambition, the defining question rises: Can reunion bloom from blighted ground? Or will this division, and our ancient, inherited curse be the doom that finally extinguishes the Ñoldor's flame?"
::EUR.KON_EREGION_DESTROY_TITLE <- @"Eregion Destroyed"

::EUR.KON_CALL_BODY <- @"The demands of the War of the Ring demand we bury our long grudges and face the future. The White Council now confronts the dream long forsaken: Ñoldorin unity. The path to peace is arduous, and will be forged in the crucible of our shared suffering. Yet, these deep scars of war leave no alternative. The Kindreds of the Elves cannot be left to their own devices. We must pave a new path, or perish in the ruins of the old."
::EUR.KON_CALL_TITLE <- @"Call for Unity"

::EUR.KON_COUNCIL_CHOICE_BODY <- @"Envoys from Lindon and Imladris meet to chart a course for Ñoldorin unity. They hope to draft binding pacts and alliances, and to silence any chance for a fifth, accursed, Kinslaying. Crucially, they propose rebuilding a King's City, to act as a symbolic capital of a Kingdom restored, that we may rise defiant from the precipice of ruin.   (Ost-In-Edhil if Imladris and Ost-in-Ñoldor if Lindon)"
::EUR.KON_COUNCIL_CHOICE_TITLE <- @"Council of Reunification"

::EUR.KON_COUNCIL_CHOICE_A_BODY <- @"In a solemn and grand ceremony, the Elves of Lindon and Imladris embraced their united future. The Kingdom of Ñoldor may be rising as an echo of old glories, but it has also been tempered by the failings of its forebears. The banners of unity are unfurled at last, and a renewed, tentative, hope dawns over the funeral pyres of those who gave their lives. The kindreds of the Ñoldor may yet have a future in this world."
::EUR.KON_COUNCIL_CHOICE_A_TITLE <- @"The Kingdom of the Ñoldor"

::EUR.KON_COUNCIL_CHOICE_R_BODY <- @"Despite the fervent pleas for unity, the old, festered wounds of strife are too grievous among the Ñoldor. This learned mistrust is a cold and stubborn fog that clings to the hearts of the gathered lords. “This reunited Kingdom,” they say, “is an impossibility. The grievances are too many, and far too painful…” The council dissolves not with a great proclamation, but with weary, reluctant acknowledgement. The dream of a united Ñoldorin Kingdom, a thing so precious at its kindling, gutters and dies once more. Its fragile light is extinguished, and now passes into the long shadows of history's failures. We are doomed to be the fading echo of things that might have been."
::EUR.KON_COUNCIL_CHOICE_R_TITLE <- @"A Grim Reality"


//KINGDOM OF EREGION

::EUR.KOE_KINSLAYING_BODY <- @"In the small hours of the night, crowned by the Star of Earendil among the raiment of the heavens, Prince Maernil gave a baleful benediction to all that gathered to follow him. His spirit blazed in the unseen realm with the wrathful fire of restoration, and his voice rang like a clarion's call.

""The Reckoning begins! They will call us Kinslayers, my faithful! I say that our cause is just, and stake my claim as the true heir of Eregion's glory! We march, not to war, but to the liberation of all Elvendom! We shall reclaim what was stolen, as ancient oaths are renewed that shall never go unanswered, so too shall we go forth and carry the light into the Fourth Age of this world! The Petty Kingdoms of Lindon and Imladris, drowning in the twinned shrouds of cowardice and compromise, stand as usurpers in the path of our united destiny. We do not draw our Blades against kin, but against traitors to the furious, fiery, souls of the Ñoldor! Our Banners fly high, calling all Elves to cast off their chains and step out of the shadow of Men! Men, who are fickle, contentious, and quick to corrupt. The 'White Council' would have us yield this world our very ancestors died to forge! It is through the cleansing fire of conflict that we shall forge our true destiny, and reclaim the birthright for which we were created!"" 
Defeat both Imladris and Lindon."
::EUR.KOE_KINSLAYING_TITLE <- @"Maernil's Reckoning, The Fourth Kinslaying"

::EUR.KOE_PART_1_BODY <- @"Stronghold by stronghold, the hosts of the faithless crumble before our might! Our furious, righteous, cause is a cleansing inferno! The last heir of Fëanor's legacy stands wreathed in fell majesty, and in his name we shall sweep this land clean of the weakness of these so-called 'Wise'! See how the treacherous stars of Lindon and Imladris dim, eclipsed by the storm of our sacred retribution! The path has been forged in fire and blood. Make no mistake… for where we now go, there can be no retreat. So we must carry only forward, driving onward to the dream of a reborn Eregion, or we shall drown in the ashes of our own treachery."
::EUR.KOE_PART_1_TITLE <- @"Twilight of the Wise"

::EUR.KOE_PART_2_BODY <- @"The war is won. Yet, the echoes of our righteous slaughter still ring through Eriador and leave a dark, indelible brand upon the Kingdom of Eregion. This Reckoning has forged us anew, and its fire leaves a bitter mark upon all Ñoldor who dared reach for our destiny. We know, in our hearts, that The Doom of Mandos stands. The Ñoldor are banished from the Uttermost West, and our fate is now bound irrevocably to Middle Earth. Before the High Prince can ascend as High King, the shattered remnants of the High King's throne must be reforged. This act is no mere ceremony; it is a symbolic lighting of the brazier. It is the resurrection of our ancient lineage that we have taken from the very ashes of Sauron's treachery. We shall not diminish and go into the west as the White Council bade us to do... We will see that Earendil's Star forever shines on the Kingdom of Eregion."
::EUR.KOE_PART_2_TITLE <- @"The Doom of the Ñoldor"

::EUR.KOE_FORM_BODY_1 <- @"Under the cold, judgmental gaze of the stars, " 
::EUR.KOE_FORM_BODY_2 <- @" ascends the restored throne of the High King. His crown, made of coiled silver and captured starlight, is more than a mere symbol of ambition achieved... it is a memorial for the lost hopes of the House of Feanor. The ghosts of Alqualondë, of Beleriand, and Celebrimbor himself, seem to coil in the periphery, their lamentations a haunting, true anthem of the High King's reign. Yet, defiant against their whispers, the Kingdom of Eregion has been dragged, through bitter effort, from the pyre of History, and will stand as a Monument to the triumph of Will over Wisdom. The future is Ours, alone, to shape. It may seem that this is a poisoned chalice grasped with hands gloved in the blood of our divorced kindreds, but it matters not. Of one thing the Wise were correct. The Ruling Ring must be found. It is an heirloom of our house, and whether it is to be claimed or destroyed is our choice alone. The throne's foundations already tremble with the weight of the King's Ascendant oath. Whether the future we forge for this world is for Good, or Ill, shall be writ only in the annals of History. We can only hope that those annals are to be written in our hand."
::EUR.KOE_FORM_TITLE <- @"The Lord of the West"

::EUR.L_CAP_LOST_TITLE <- @"The Grey Havens burn"
::EUR.L_CAP_UNLOST_TITLE <- @"Mithlond Retaken"
::EUR.L_CAP_LOST_BODY <- @"Ai! Grave tidings from Mithlond, Lord. The Harbours of Cirdan, which have stood since the breaking of Beleriand, have been set aflame by the goblin hordes. Their foul beasts roam through the stables and yards, their trolls smash ancient statues depicting Earendil the Mariner and long mourned Elven Lords of old. Mithlond must be retaken, and its Harbors restored; that we may once again ferry those heeding the Call of the Sea into the uttermost west. Those who gave their lives in defense of the city are now in the Halls of Mandos, and are now beyond the reach of any Earthly pain. To the Fallen we say, “Nai hiruvalyë Valimar! Namárië!” May we meet again, in the remaking of the World."
::EUR.L_CAP_UNLOST_BODY <- @"Utúlie'n aurë! The Goblin Horde has been cast out of Mithlond! Even now, the Eldar prowl the streets and alleys of the blessed city, hunting stray Goblins and War Beasts with wrathful vigor. We have returned to the Ancient City as victorious reclaimers. Yet, this is not a time for festivals and the revels of victory, for the threat is not yet vanquished. The bodies of the Fallen, mutilated and devoured by the Orcs and their beasts, must be given the proper rites, and in time new statues will be erected honoring their sacrifices.

The Enemy's Strength is scattered, but still it waxes with the growing Shadow in the East. Perhaps this is a sign that the Elves should once again take an active part in the events of the World. There are voices who ask, are we not helping the Enemy in our apathy? They may be right... Regardless, the current path is clear. The Blue Mountains must be cleansed of the Goblin Filth, and our shores guarded against the Corsair raiders, for if we cannot protect our own homes, then what hope would Men have when the Shadow Darkens their lands?

Only a Fool's Hope."

::EUR.I_CAP_LOST_TITLE <- @"Imladris lost"
::EUR.I_CAP_UNLOST_TITLE <- @"Rivendell Reclaimed"
::EUR.I_CAP_LOST_BODY <- @"Tragedy! The Last Homely House, which has given succor to the Free Peoples of Middle Earth since Sauron's War in Eregion, has fallen. The Goblins of Moria, spurred on by a terror greater than any artifice of Lord Elrond, have overcome the wards and bastions guarding the Hidden Valley. As the last bridges were lost, a vanguard formed, Elves and Dunedain who knew that this was their last sunset, and held the pass open as the Women and Children were ferried to Safety. Bilbo Baggins, a beloved guest of Lord Elrond, was carried away by a small band of Rangers who honored their oath to guard the Shire and its people. Bitter tears were shed by those who sought to break the siege, for the flames burned so brightly that they shone over the warding mountains and hills like a beacon. We were too late to rescue the City, but those who died can be avenged."
::EUR.I_CAP_UNLOST_BODY <- @"The Hidden Valley is once again under the protection of Lord Elrond. Our Armies descended upon Rivendell with the Wrath of Tulkas and the Vigor of Nessa the Swift, cleansing the streams and channels of Orc filth. The Rivers that ran Crimson with the blood of our fallen, now run black with the blood of Rivendell's Despoilers. It is a grave wound we were dealt, for we underestimated the resolve and cunning of our foe. Never again. There are voices that call for us to unleash our full might upon the Enemy, that we should be passive observers no longer. Once, some say, we were the Stewards of Arda, and yet we have been watching her decline with acceptance.

Yet, the threat is not yet ended. For the Goblin Warrens of the Misty Mountains have many hollows and pits to breed more of their wretched race. Shatter their armies, drive them back into their pits, and remind them why they cower beneath the ground. Only then may may we turn our thoughts to the Future."

::EUR.EREGION_KD_NOTIF_TITLE <- @"Reforging an Ancient Brotherhood"
::EUR.EREGION_KD_NOTIF_BODY <- @"From the initial foundation of our Kingdom, The Lords of Eregion fostered strong relations with the Dwarves of Khazad-Dûm. The Doors of Durin were carved by the joint craft of Narvi and Lord Celebrimbor, and stood testament to the lifelong bonds forged between our two peoples. Now, Eregion is reclaimed, and the Son of Fundin seeks to cleanse the ancient Dwarf City of Dwarrowdelf. Already, the Doors of Durin have vomited forth hordes or orcs, imprisoning our High Prince, and subjecting him to centuries of long torment. If we forge an alliance with them, we shall both be made stronger for it, and shall be able to once again unify our craft, welcoming some of the Dwarves to live among us, and reforging the Order of Avengers."

// ==============================================================================================
// Settlement model-swap events (from eurCasLoad.lua)
// ==============================================================================================

::EUR.caras_galadhon_corrupted_body <- @"The heart of the Golden Realm has fallen… The lands of the Galadhrim, having long stood defiant against the encroaching darkness, are drowned beneath the tide of the Servants of Evil. The ageless boughs, and the filtered golden shade, are new hewn and burn the ground the black of orc blood. Even if it is retaken, it shall never be the same…"
::EUR.caras_galadhon_corrupted_title <- @"Caras Galadhon in flames!"
::EUR.helms_deep_corrupted_body <- @"The Fires of Industry have claimed Helm’s Deep. Long has the Deeping Wall stood as a redoubt against those who would kill the sons of the Hammerhand. Now, the wall is studded with steel, and the craft of Saruman set into the very stone. Ost-Curunír he calls it, for it has become his fortress, and crown jewel. A symbol of hope for the Eoreds now a permanent reminder of their failures, and Saruman’s ascendancy!"
::EUR.helms_deep_corrupted_title <- @"The Deeping Wall is broken!"
::EUR.anorien_corrupted_body <- @"Tragedy! The Tower of Guard burns. The people flee in a tide of stinking fear to the upper levels, and everywhere are pursued by the Armies of Shadow. The Steward’s whereabouts are unknown, and it is said that the White Tree was set aflame by the jeering foes of the line of Anarion. The last of the great bastions of the Numenorean exiles stands now as a dark pit of slavery and torment, and the people of Gondor wonder if there shall ever be a new dawn for Men."
::EUR.anorien_corrupted_title <- @"The White Tree burns!"
::EUR.anorien_cleansed_body <- @"The streets of Minas Tirith are filled with cheers, for the White City has been reclaimed from the Armies of Shadow. Those who survived the revels of the City’s conquest are now liberated from their slavery, and stand newly defiant against the Shadow in the East. Already, the wrath of the Edain surges to avenge the fallen, and a glimmer of hope dawns, for the White Tree shows a solitary bud, defiant against the flames which marred it."
::EUR.anorien_cleansed_title <- @"The Tower of Guard reclaimed!"
::EUR.isengard_cleansed_body <- @"The gauntleted fist of the White Hand, Isengard, has fallen to the Free Peoples of Middle-Earth. The Ancient fortress of Angrenost and the Orthanc Stone within, were bequeathed to Saruman the White by the King of Rohan and Steward of Gondor when he returned from his pilgrimage through the Far East. Following the Treason of Saruman the White, the land was scarred, and pits were dug as the Wizard began working in service to the Shadow in the East. No longer is this the Vale of the Wizard! Now, the fortress, and the great tower of Orthanc in its heart, will once again be a shield to guard the fords of Isen. Even now, the Ents have shepherd many young and lively trees to reclaim the ruined ground, and the Isen once again flows."
::EUR.isengard_cleansed_title <- @"Nature reclaims Angrenost!"
::EUR.amon_sul_restored_body <- @"Amon Sûl, the ruined watchtower of Elendil the Tall, stands as warden over Arnor’s northernmost borders once again! Though its Palantir still rests at the bottom of the Bay of Forochel, the beacon flame blazes defiant against the darkness that had long threatened these lands, and is a symbol of the renewed strength of Arnor! The Kingdom of the North is no longer blind, and its people shall always be protected by the light of the Dúnedain."
::EUR.amon_sul_restored_title <- @"Amon Sûl rebuilt!"
::EUR.tharbad_restored_body <- @"Once a trade city to rival Pelargir, and Umbar, Tharbad was abandoned to the tribesmen by Gondor when it began to wane. Yet, that time has passed, the descendants of Numenor have restored the city’s walls, the Bridge of Tharbad once again spans the Gwathlo, and the river is a restored avenue of trade for the City’s Lords."
::EUR.tharbad_restored_title <- @"Tharbad restored!"
::EUR.amon_lanc_cleansed_body <- @"The Naked Hill has been snatched from the grasp of Sauron’s Servants and purified of the foul corruption of the Dark Lord. It is no longer a haven of Necromancers and orcs, its dark altars have been cast down, and the light of the Eldar returns to its ancient bastion. Amon Lanc stands as a blazing, defiant, beacon against the joint shadows of Mirkwood and Mordor, and the Free Peoples know now that the Lady of Lorien stands alongside them."
::EUR.amon_lanc_cleansed_title <- @"Dol Guldur cleansed!"
::EUR.minas_ithil_cleansed_body <- @"Minas Morgul, long coveted and held by the Witch King of Angmar, in service to the Dark Tower, has been cleansed of the filth that long marred the Moon Tower of Isildur. The descendants of the Realms in Exile have long wished to revenge themselves for the loss of Minas Anor’s sister city, and now their voices are raised in triumph. The Shadow is broken! The Bulwarks of the Black Land fall, and for the first time since Sauron returned to Mordor, we have hope that this terrible war may soon end."
::EUR.minas_ithil_cleansed_title <- @"Minas Ithil scoured!"
