
::EUR.EDUOFFET_SETT_VARS <- null
::EUR.INPUT_TEXT_FOCUSED <- false
::EUR.UI_MANAGER <- null
::EUR.alt_checked <- false
::EUR.alt_exp_unit <- null
::EUR.alt_kills_unit <- null
::EUR.block_poe_turns <- 0
::EUR.conquer_traits_units <- null
::EUR.diplo_open <- false
::EUR.edumodActive <- false
::EUR.edumodTurnsRemain <- 0
::EUR.eur_event_active <- false
::EUR.eur_event_activelen <- 0
::EUR.eur_event_min_cooldown <- 0
::EUR.eur_spawned_characters <- 0
::EUR.growthTurnsRemain <- 0
::EUR.mirrorTarget <- null
::EUR.mirrorTurnsRemain <- 0
::EUR.modify_growth <- false
::EUR.replen_bonus <- 0
::EUR.scroll_unit <- null
::EUR.sel_unit <- null
::EUR.can_bg_swap <- false
::EUR.can_unit_upgrade <- false
::EUR.show_buildfort <- false
::EUR.swap_bg_window <- null
::EUR.traitToAdd <- null
::EUR.traitTurnsRemain <- 0
::EUR.tulkasActive <- false
::EUR.tulkasTurnsRemain <- 0

::EUR.sort_option <- null
::EUR.UNIT_UPGRADES <- {}

::EUR.lindon_0_count <- 0
::EUR.extents_entries <- {}
::EUR.fert_level <- 0
::EUR.show_bg_accept <- false
::EUR.swap_bg_button <- null
::EUR.xScale <- 1.0
::EUR.battleBuildingType <- ::Enum.BattleBuildingType

::EUR.ELVEN_FACTIONS <- {}
::EUR.addSetts <- null
::EUR.addSettsBu <- null
::EUR.aiPlan <- ::Enum.BattleAiPlan
::EUR.battleType <- ::Enum.BattleType
::EUR.event_number <- null
::EUR.eyeTarget <- null
::EUR.faction_upgrade_card_silver <- null
::EUR.moraleStatus <- ::Enum.UnitMorale
::EUR.saved_already_pre <- null
::EUR.tempmirrorTarget <- null
::EUR.unitAction <- ::Enum.UnitOrder
::EUR.unitBattleProperties <- ::Enum.UnitBattleProperty
::EUR.unitStatus <- ::Enum.UnitActionStatus
::EUR.unit_only <- null

::EUR.anor <- null
::EUR.button_01 <- null
::EUR.coins <- null
::EUR.crown1 <- null
::EUR.crown1locked <- null
::EUR.eldarlight <- null
::EUR.ent1 <- null
::EUR.eregion_icon <- null
::EUR.eregion_rebellion_choice <- 0
::EUR.hammer <- null
::EUR.icon_options <- null
::EUR.icon_unit <- null
::EUR.icon_unit2 <- null
::EUR.imladris_icon <- false
::EUR.imladris_kon_icon <- false
::EUR.koe_title <- null
::EUR.kon_council_choice <- 0
::EUR.kon_title <- null
::EUR.lindon_icon <- null
::EUR.lindon_kon_icon <- null
::EUR.lordsgondor <- null
::EUR.mengood_pic_0 <- null
::EUR.mirror1 <- null
::EUR.oatheorl <- null
::EUR.orome <- null
::EUR.revive_no <- null
::EUR.revive_yes <- 0
::EUR.ship1 <- null
::EUR.ship1locked <- null
::EUR.stew1 <- null
::EUR.stew1locked <- null
::EUR.test1 <- null
::EUR.tulkas <- null
::EUR.ulmo <- null
::EUR.yavanna <- null
::EUR.faction_upgrade_card_bw <- {}
::EUR.faction_upgrade_card_bronze <- {}
::EUR.faction_upgrade_card_blue <- {}
::EUR.faction_upgrade_card_gold <- {}
